/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TiketPesawat.views;

import TiketPesawat.controller.DaftarController;

/**
 *
 * @author user
 */
public class DaftarView extends javax.swing.JFrame {

    DaftarController dc;
    public DaftarView(DaftarController c) {
        initComponents();
        this.dc = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        daftarBtn = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 95, 190, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 190, -1));

        daftarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TiketPesawat/img/daftarView-DaftarBtn.png"))); // NOI18N
        daftarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarBtnMouseClicked(evt);
            }
        });
        getContentPane().add(daftarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 200, -1, 30));

        kembaliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TiketPesawat/img/daftarView-KembaliBtn.png"))); // NOI18N
        kembaliBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliBtnMouseClicked(evt);
            }
        });
        getContentPane().add(kembaliBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 238, -1, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 165, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TiketPesawat/img/bg-DaftarView.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daftarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarBtnMouseClicked
        // TODO add your handling code here:
         dc.daftarUser(nama.getText(), email.getText(), username.getText(), password.getText());
    }//GEN-LAST:event_daftarBtnMouseClicked

    private void kembaliBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliBtnMouseClicked
        // TODO add your handling code here:
        dc.keMasuk();
    }//GEN-LAST:event_kembaliBtnMouseClicked

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarBtn;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JTextField nama;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
