package TiketPesawat.views;

import TiketPesawat.controller.JadwalController;
import TiketPesawat.helper.DBJadwal;
import TiketPesawat.model.JadwalModel;
import java.awt.*;
import java.sql.*;
import javax.swing.JTable;

public class JadwalView extends javax.swing.JFrame {

    JadwalController jc;

    public JadwalView(JadwalController c) {
        initComponents();
        this.jc = c;
        kodeMaskapai.removeAllItems();
        kotaAwal.removeAllItems();
        kotaTujuan.removeAllItems();
        loadDataPesawat();
        loadDataKota();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kodeJadwal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jamKeberangkatan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kodeMaskapai = new javax.swing.JComboBox<>();
        kotaAwal = new javax.swing.JComboBox<>();
        kotaTujuan = new javax.swing.JComboBox<>();
        ubahBtn = new javax.swing.JButton();
        tambahBtn = new javax.swing.JButton();
        cleatBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jadwalTabel = new javax.swing.JTable();
        hapusBtn = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();
        jamKedatangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kursiTersedia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        statusKuota = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        kursiDiambil = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Halaman Jadwal");

        jLabel2.setText("Kode Jadwal");

        jLabel3.setText("Jam Keberangkatan");

        jLabel4.setText("Jam Kedatangan");

        jLabel5.setText("Harga");

        jLabel6.setText("Kode Maskapai");

        jLabel7.setText("Kota Awal");

        jLabel8.setText("Kota Tujuan");

        kodeMaskapai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        kotaAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        kotaTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ubahBtn.setText("Ubah");
        ubahBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ubahBtnMouseClicked(evt);
            }
        });

        tambahBtn.setText("Tambah");
        tambahBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahBtnMouseClicked(evt);
            }
        });

        cleatBtn.setText("Clear");
        cleatBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cleatBtnMouseClicked(evt);
            }
        });

        jadwalTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jadwalTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jadwalTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jadwalTabel);

        hapusBtn.setText("Hapus");
        hapusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusBtnMouseClicked(evt);
            }
        });

        kembaliBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TiketPesawat/img/daftarView-KembaliBtn.png"))); // NOI18N
        kembaliBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliBtnMouseClicked(evt);
            }
        });
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Kursi Yang Tersedia");

        jLabel10.setText("Kursi Yang Telah Diambil");

        jLabel11.setText("Status Kuota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cleatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ubahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tambahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(statusKuota, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(kursiDiambil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                .addComponent(kursiTersedia, javax.swing.GroupLayout.Alignment.LEADING)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembaliBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(kodeMaskapai, javax.swing.GroupLayout.Alignment.LEADING, 0, 134, Short.MAX_VALUE)
                                                .addComponent(kodeJadwal, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(harga)
                                                .addComponent(jamKeberangkatan, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(kotaTujuan, javax.swing.GroupLayout.Alignment.TRAILING, 0, 135, Short.MAX_VALUE)
                                                .addComponent(kotaAwal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jamKedatangan)))))
                                .addGap(302, 302, 302))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kodeJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kodeMaskapai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(kotaAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(kotaTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jamKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jamKedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kursiTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(kursiDiambil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(statusKuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubahBtn)
                            .addComponent(tambahBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cleatBtn)
                            .addComponent(hapusBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kembaliBtn)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleatBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cleatBtnMouseClicked
        // TODO add your handling code here:
        kodeJadwal.setText("");
        harga.setText("");
        jamKeberangkatan.setText("");
        jamKedatangan.setText("");
        kodeJadwal.setEnabled(true);
    }//GEN-LAST:event_cleatBtnMouseClicked

    private void tambahBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahBtnMouseClicked
        // TODO add your handling code here:
        String pesawat = String.valueOf(kodeMaskapai.getSelectedItem());
        String kotaawal = String.valueOf(kotaAwal.getSelectedItem());
        String kotatujuan = String.valueOf(kotaTujuan.getSelectedItem());
        
        jc.addData(
                kodeJadwal.getText(),
                pesawat,
                kotaawal,
                kotatujuan,
                jamKeberangkatan.getText(),
                jamKedatangan.getText(),
                harga.getText(),
                kursiTersedia.getText(),
                kursiDiambil.getText()
        );
    }//GEN-LAST:event_tambahBtnMouseClicked

    private void ubahBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubahBtnMouseClicked
        // TODO add your handling code here:
        int row = jadwalTabel.getSelectedRow();
        String pesawat = String.valueOf(kodeMaskapai.getSelectedItem());
        String kotaawal = String.valueOf(kotaAwal.getSelectedItem());
        String kotatujuan = String.valueOf(kotaTujuan.getSelectedItem());

        jc.updateData(
                row,
                kodeJadwal.getText(), // ID Jadwal tetap tidak berubah
                pesawat,
                kotaawal,
                kotatujuan,
                jamKeberangkatan.getText(),
                jamKedatangan.getText(),
                harga.getText(),
                kursiTersedia.getText(),
                kursiDiambil.getText()
        );
        kodeJadwal.setEnabled(false); // Pastikan tetap nonaktif
    }//GEN-LAST:event_ubahBtnMouseClicked

    private void hapusBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusBtnMouseClicked
        // TODO add your handling code here:
        int row = jadwalTabel.getSelectedRow();
        jc.hapusData(row);
    }//GEN-LAST:event_hapusBtnMouseClicked

    private void jadwalTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jadwalTabelMouseClicked
        // TODO add your handling code here:
        int row = jadwalTabel.getSelectedRow();
        String a = jadwalTabel.getValueAt(row, 0).toString();
        String b = jadwalTabel.getValueAt(row, 1).toString();
        String c = jadwalTabel.getValueAt(row, 2).toString();
        String d = jadwalTabel.getValueAt(row, 3).toString();
        String e = jadwalTabel.getValueAt(row, 4).toString();
        String f = jadwalTabel.getValueAt(row, 5).toString();
        String g = jadwalTabel.getValueAt(row, 6).toString();
        String h = jadwalTabel.getValueAt(row, 7).toString();
        String j = jadwalTabel.getValueAt(row, 8).toString();
        String k = jadwalTabel.getValueAt(row, 9).toString();
        kodeJadwal.setText(a);
        kodeJadwal.setEnabled(false); // Tetap nonaktif

        for (int i = 0; i < kodeMaskapai.getWidth(); i++) {
            String z = kodeMaskapai.getItemAt(i);
            if (z.substring(0, 4).equals(b)) {
                kodeMaskapai.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < kotaAwal.getItemCount(); i++) {
            String z = kotaAwal.getItemAt(i);
            if (z != null && z.length() >= 4 && z.substring(0, 4).equals(c)) {
                kotaAwal.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < kotaTujuan.getItemCount(); i++) {
            String z = kotaTujuan.getItemAt(i);
            if (z != null && z.length() >= 4 && z.substring(0, 4).equals(d)) {
                kotaTujuan.setSelectedIndex(i);
                break;
            }
        }
        jamKeberangkatan.setText(e);
        jamKedatangan.setText(f);
        harga.setText(g);
        kursiTersedia.setText(h);
        kursiDiambil.setText(j);
        statusKuota.setText(k);
        statusKuota.setEnabled(false);
    }//GEN-LAST:event_jadwalTabelMouseClicked

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliBtnActionPerformed

    // Methode yang dipakai
    private void kembaliBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_kembaliBtnMouseClicked
        // TODO add your handling code here:
        jc.keAdmin();
    }// GEN-LAST:event_kembaliBtnMouseClicked

//    tambahan sendiri

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleatBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jadwalTabel;
    private javax.swing.JTextField jamKeberangkatan;
    private javax.swing.JTextField jamKedatangan;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JTextField kodeJadwal;
    private javax.swing.JComboBox<String> kodeMaskapai;
    private javax.swing.JComboBox<String> kotaAwal;
    private javax.swing.JComboBox<String> kotaTujuan;
    private javax.swing.JTextField kursiDiambil;
    private javax.swing.JTextField kursiTersedia;
    private javax.swing.JTextField statusKuota;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton ubahBtn;
    // End of variables declaration//GEN-END:variables

    public JTable getJadwalTabel() {
        return jadwalTabel;
    }

    private void loadDataPesawat() {
        java.util.List<JadwalModel> dataPesawat = jc.loadDataPesawat();
        for (JadwalModel m1 : dataPesawat) {
            kodeMaskapai.addItem(m1.getKodePesawat() + " - " + m1.getPesawat());
        };
    }

    private void loadDataKota() {
        java.util.List<JadwalModel> dataKota = jc.loadDataKota();
        for (JadwalModel m2 : dataKota) {
            kotaAwal.addItem(m2.getKodeKota() + " - " + m2.getKota());
            kotaTujuan.addItem(m2.getKodeKota() + " - " + m2.getKota());
        };
    }

}
